feat(publish-release): use npm by default
mdn/workflows pull request #116
Opened 2023-02-09 21:29 UTC by caugner

### Description

Adds a new input "package-manager", defaulting to "npm".

Also bumps the Node.js version to 16.

### Motivation

This currently blocks the release of `@mdn/bob` v3.0.0, which has migrated to npm.

### Additional details

### Related issues and pull requests

See the workflow runs on [this commit](https://github.com/mdn/bob/commit/8df94dd1a08125ce83a55233429726500cfc779f).

2023-02-09 23:43 UTC, queengooborg commented
I just opened #117 to try and add the same input... 🙃

2023-02-09 23:54 UTC, queengooborg requested changes

2023-02-09 23:54 UTC, queengooborg commented on .github/workflows/publish-release.yml
>            registry-url: '${{ inputs.registry-url }}'
```suggestion
          registry-url: '${{ inputs.registry-url }}'
          cache: ${{ inputs.cache }}
```

2023-02-09 23:54 UTC, queengooborg commented on .github/workflows/publish-release.yml
> +      package-manager:
Small nit: may we rename this argument to `cache`?  It's the variable name used by other workflows, including GitHub's own.

2023-02-09 23:54 UTC, queengooborg commented on .github/workflows/publish-release.yml
> +        if: inputs.npm-publish && steps.release.outputs.release_created && inputs.package-manager == 'yarn'
```suggestion
        if: inputs.npm-publish && steps.release.outputs.release_created && inputs.cache == 'yarn'
```

2023-02-09 23:54 UTC, queengooborg commented on .github/workflows/publish-release.yml
> +        if: inputs.npm-publish && steps.release.outputs.release_created && inputs.package-manager == 'npm'
```suggestion
        if: inputs.npm-publish && steps.release.outputs.release_created && inputs.cache == 'npm'
```

2023-02-09 23:54 UTC, queengooborg commented on .github/workflows/publish-release.yml
> +        default: npm
To avoid breaking any projects that are still using Yarn, maybe we should keep the default as `yarn` and change it to `npm` later:

```suggestion
        default: yarn
```

2023-02-10 08:44 UTC, caugner commented on .github/workflows/publish-release.yml
> +      package-manager:
I feel like `cache` is ambiguous at this level (the `publish-release` workflow), whereas `package-manager` is very clear and explicit.

2023-02-10 08:44 UTC, caugner commented on .github/workflows/publish-release.yml
>            registry-url: '${{ inputs.registry-url }}'
I think it's safer to _not_ use the cache when building and publishing a release. We don't run this workflow that often, so we don't need to speed it up at the cost of potentially stumbling upon a cache invalidation problem.

2023-02-10 08:46 UTC, queengooborg commented on .github/workflows/publish-release.yml
> +      package-manager:
Gotcha -- in that case, we should probably change our other workflows to use `package-manager` instead of `cache` for consistency.

2023-02-10 08:52 UTC, caugner commented on .github/workflows/publish-release.yml
> +        default: npm
I checked and we don't use this workflow in a lot of repos:

<img width="502" alt="image" src="https://user-images.githubusercontent.com/495429/218045972-f3e57108-eed1-41bb-849f-e7eb3d9ed549.png">

- `interactive-examples` has an [open PR to migrate to npm](https://github.com/mdn/interactive-examples/pull/2388)
- `data` had never been migrated to yarn in the first place (so it seems)
- `markdown` will be archived anytime soon and won't have further releases
- `bob` has already been migrated to npm
- `mdn-minimalist` has already been archived

This is almost enough evidence to ditch the option altogether and simply migrate to `npm ci`.

2023-02-10 08:56 UTC, caugner commented on .github/workflows/publish-release.yml
> +      package-manager:
Oh sorry, I didn't realize other workflows **in this repo** have a `cache` input.

2023-02-10 09:43 UTC, caugner commented on .github/workflows/publish-release.yml
> +      package-manager:
Input removed in 9c2789f.

2023-02-10 09:43 UTC, caugner commented on .github/workflows/publish-release.yml
> +        default: npm
Input removed in 9c2789f.

2023-02-10 09:43 UTC, caugner commented on .github/workflows/publish-release.yml
> +        if: inputs.npm-publish && steps.release.outputs.release_created && inputs.package-manager == 'npm'
Input removed in 9c2789f.

2023-02-10 09:43 UTC, caugner commented on .github/workflows/publish-release.yml
> +        if: inputs.npm-publish && steps.release.outputs.release_created && inputs.package-manager == 'yarn'
Input removed in 9c2789f.

2023-02-10 10:00 UTC, caugner commented on .github/workflows/publish-release.yml
> +      - run: npm ci
Oops:

```suggestion
      - run: npm ci
        if: inputs.npm-publish && steps.release.outputs.release_created
```

2023-02-10 10:02 UTC, caugner commented on .github/workflows/publish-release.yml
> +        default: 16
Revert in favor of https://github.com/mdn/workflows/pull/118:

```suggestion
        default: 12
```

2023-02-10 10:03 UTC, caugner commented
@queengooborg I have now reduced the scope of this PR to just migrate to npm.

2023-02-10 10:04 UTC, queengooborg approved these changes
LGTM, thank you!

2023-02-10 12:00 UTC, schalkneethling approved these changes

2023-02-10 12:00 UTC, merged