Create action for "rebase needed" autolabeler
mdn/workflows pull request #33
Opened 2022-04-27 21:31 UTC by queengooborg

Created at the request of @schalkneethling (see https://github.com/mdn/browser-compat-data/pull/15931#issuecomment-1111316493).  This PR adds a GitHub Actions workflow to automatically (un)label pull requests that have merge conflicts.

2022-04-28 09:20 UTC, schalkneethling requested changes
Thanks so much, @queengooborg! Exciting to see this repo grow with so many useful actions. A couple of items to address.

2022-04-28 09:20 UTC, schalkneethling commented on README.md
> +- This `input` is optional with a default of `rebase needed`
I would say let’s make the one with the emoji the default.  I am trying to make things look a little more fun by using emojis in general 😸

2022-04-28 09:20 UTC, schalkneethling commented on README.md
> +In the repository that will call this action, you will need to add a `.github/workflows/publish-release.yml` file with the following content:
I assume you meant:

```suggestion
In the repository that will call this action, you will need to add a `.github/workflows/pr-rebase-needed.yml` file with the following content:
```

2022-04-28 09:20 UTC, schalkneethling commented on README.md
> +
I don’t think we need this right?

2022-04-28 09:20 UTC, schalkneethling commented on .github/workflows/pr-rebase-needed.yml
> +          commentOnDirty: ${{ inputs.comment }}
Is this not missing something like this:

https://github.com/mdn/workflows/blob/b914d5dfefe6b9e903890d1522db66ec41bcbf50/.github/workflows/publish-release.yml#L35

2022-04-28 22:00 UTC, queengooborg commented on .github/workflows/pr-rebase-needed.yml
> +          commentOnDirty: ${{ inputs.comment }}
It's right on line 27!

2022-04-29 14:08 UTC, schalkneethling approved these changes
Thank you, @queengooborg 🎉

2022-04-29 14:08 UTC, merged