feat: support add a comment on staling or closing issue/pr
mdn/workflows pull request #75
Opened 2022-08-14 08:19 UTC by yin1999

Fixes: #56

See: https://github.com/actions/stale#stale-issue-message

2023-06-30 13:26 UTC, bsmth commented
There's another one open in https://github.com/mdn/workflows/pull/123 - should we wait for that to land first?

2023-06-30 13:41 UTC, yin1999 commented
> There's another one open in #123 - should we wait for that to land first?

Sure, let's wait until #123 is landed :)

2023-09-06 06:58 UTC, uiolee approved these changes

2023-10-12 11:41 UTC, caugner requested changes
LGTM, but found a typo and suggested some less verbose descriptions.

2023-10-12 11:41 UTC, caugner commented on .github/workflows/idle.yml
> +      close-issue-meesage:
```suggestion
      close-issue-message:
```

2023-10-12 11:41 UTC, caugner commented on .github/workflows/idle.yml
> +          close-issue-meesage: ${{ inputs.close-issue-meesage }}
```suggestion
          close-issue-message: ${{ inputs.close-issue-message }}
```

2023-10-12 11:41 UTC, caugner commented on .github/workflows/idle.yml
> +        description: The comment message will be added to the issues when closing it automatically.
```suggestion
        description: Comment to add when a stale issue is closed.
```

2023-10-12 11:41 UTC, caugner commented on .github/workflows/idle.yml
> +        description: The comment message will be added to the issue when staling it automatically.
```suggestion
        description: Comment to add when an issue becomes stale.
```

2023-10-12 11:41 UTC, caugner commented on .github/workflows/idle.yml
> +        description: The comment message will be added to the PR when closing it automatically.
```suggestion
        description: Comment to add when a stale PR is closed.
```

2023-10-12 11:41 UTC, caugner commented on .github/workflows/idle.yml
> +        description: The comment message will be added to the PR when staling it automatically.
```suggestion
        description: Comment to add when a PR becomes stale.
```

2023-10-12 13:22 UTC, caugner approved these changes

2023-10-12 13:23 UTC, merged